-- Add missing columns to users table for HR
ALTER TABLE users ADD COLUMN IF NOT EXISTS base_salary NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS afp VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS health_system VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS weekly_hours INTEGER DEFAULT 45;
