type Queryable = {
    query: (sql: string, params?: unknown[]) => Promise<unknown>;
};

export const MINIMAL_RUNTIME_TABLES = [
    'categories',
    'laboratories',
    'therapeutic_actions',
    'suppliers',
    'product_suppliers',
    'purchase_orders',
    'purchase_order_items',
    'shipments',
    'shipment_items',
    'invoice_parsings',
    'app_settings',
    'system_configs',
    'cash_register_sessions',
    'financial_accounts',
    'monthly_closings',
    'monthly_closing_entries',
    'treasury_transactions',
    'treasury_remittances',
    'refunds',
    'notifications',
    'notification_reads',
    'attendance_logs',
] as const;

export const MINIMAL_RUNTIME_COLUMNS = [
    'sales.status',
    'sales.session_id',
    'locations.email',
    'locations.manager_id',
    'locations.config',
    'products.category',
    'products.dci',
    'products.units_per_box',
    'products.price_sell_box',
    'products.price_sell_unit',
    'products.cost_net',
    'products.tax_percent',
    'products.stock_minimo_seguridad',
    'products.stock_total',
    'products.format',
    'products.laboratory',
    'products.isp_register',
    'products.is_bioequivalent',
    'products.requires_prescription',
    'products.es_frio',
    'products.barcode',
    'products.is_active',
    'products.location_id',
    'products.comisionable',
    'products.registration_source',
    'products.is_express_entry',
    'products.source_system',
    'products.created_at',
    'products.updated_at',
    'products.deactivated_at',
    'products.deactivated_by',
    'products.deactivation_reason',
    'products.condicion_venta',
    'inventory_batches.barcode',
    'inventory_batches.stock_actual',
    'inventory_batches.units_per_box',
    'inventory_batches.laboratory',
    'inventory_batches.created_at',
    'inventory_batches.is_retail_lot',
    'terminals.is_active',
    'terminals.config',
    'terminals.printer_config',
    'terminals.module_number',
    'terminals.deleted_at',
    'terminals.current_cashier_id',
    'terminals.session_id',
    'users.last_login_at',
    'users.last_login_ip',
    'cash_register_sessions.terminal_id',
    'cash_register_sessions.user_id',
    'cash_register_sessions.status',
    'cash_register_sessions.opening_amount',
    'cash_register_sessions.opened_at',
    'cash_register_sessions.closed_at',
    'cash_register_sessions.notes',
    'cash_register_sessions.closed_by_user_id',
    'cash_movements.session_id',
    'sale_items.product_id',
    'sale_items.product_name',
    'sale_items.discount_amount',
    'sale_items.timestamp',
    'sale_items.refunded_quantity',
    'monthly_closings.month',
    'monthly_closings.year',
    'monthly_closings.real_cash_income',
    'monthly_closings.real_bank_income',
    'monthly_closings.fixed_expenses',
    'monthly_closings.variable_expenses',
    'monthly_closings.payroll_cost',
    'monthly_closings.social_security_cost',
    'monthly_closings.tax_cost',
    'monthly_closings.status',
    'monthly_closings.notes',
    'monthly_closings.closed_by',
    'monthly_closings.closed_at',
    'monthly_closings.reopen_reason',
    'monthly_closings.reopened_by',
    'monthly_closings.reopened_at',
    'monthly_closing_entries.month',
    'monthly_closing_entries.year',
    'monthly_closing_entries.direction',
    'monthly_closing_entries.category',
    'monthly_closing_entries.description',
    'monthly_closing_entries.reference_date',
    'monthly_closing_entries.amount',
    'monthly_closing_entries.created_by',
    'customers.status',
    'customers.loyalty_points',
    'customers.tags',
    'customers.health_tags',
    'customers.last_visit',
    'attendance_logs.method',
    'attendance_logs.observation',
    'attendance_logs.evidence_photo_url',
    'attendance_logs.overtime_minutes',
    'attendance_logs.overtime_approved',
    'attendance_logs.overtime_approved_by',
    'attendance_logs.overtime_approval_notes',
    'categories.id',
    'categories.name',
    'laboratories.id',
    'laboratories.name',
    'therapeutic_actions.id',
    'therapeutic_actions.name',
    'suppliers.rut',
    'suppliers.business_name',
    'suppliers.status',
    'product_suppliers.product_id',
    'product_suppliers.supplier_id',
    'product_suppliers.supplier_sku',
    'purchase_orders.supplier_id',
    'purchase_orders.total_amount',
    'purchase_orders.delivery_date',
    'purchase_orders.items',
    'purchase_orders.notes',
    'purchase_order_items.purchase_order_id',
    'purchase_order_items.quantity_ordered',
    'purchase_order_items.quantity_received',
    'shipments.origin_location_id',
    'shipments.destination_location_id',
    'shipments.transport_data',
    'shipments.created_by',
    'shipments.notes',
    'shipment_items.shipment_id',
    'shipment_items.product_id',
    'shipment_items.condition',
    'shipment_items.notes',
    'invoice_parsings.supplier_rut',
    'invoice_parsings.supplier_name',
    'invoice_parsings.supplier_address',
    'invoice_parsings.supplier_phone',
    'invoice_parsings.supplier_email',
    'invoice_parsings.supplier_website',
    'invoice_parsings.supplier_activity',
    'invoice_parsings.supplier_fantasy_name',
    'invoice_parsings.document_type',
    'invoice_parsings.invoice_number',
    'invoice_parsings.issue_date',
    'invoice_parsings.due_date',
    'invoice_parsings.net_amount',
    'invoice_parsings.tax_amount',
    'invoice_parsings.total_amount',
    'invoice_parsings.discount_amount',
    'invoice_parsings.parsed_items',
    'invoice_parsings.document_notes',
    'invoice_parsings.raw_ai_response',
    'invoice_parsings.ai_provider',
    'invoice_parsings.ai_model',
    'invoice_parsings.processing_time_ms',
    'invoice_parsings.confidence_score',
    'invoice_parsings.validation_warnings',
    'invoice_parsings.status',
    'invoice_parsings.total_items',
    'invoice_parsings.mapped_items',
    'invoice_parsings.unmapped_items',
    'invoice_parsings.supplier_id',
    'invoice_parsings.supplier_created',
    'invoice_parsings.account_payable_id',
    'invoice_parsings.reception_id',
    'invoice_parsings.original_file_type',
    'invoice_parsings.original_file_name',
    'invoice_parsings.original_file_size',
    'invoice_parsings.original_file_hash',
    'invoice_parsings.original_file_data',
    'invoice_parsings.location_id',
    'invoice_parsings.created_by',
    'invoice_parsings.created_at',
    'invoice_parsings.validated_by',
    'invoice_parsings.validated_at',
    'invoice_parsings.processed_by',
    'invoice_parsings.processed_at',
    'invoice_parsings.rejected_by',
    'invoice_parsings.rejected_at',
    'invoice_parsings.rejection_reason',
    'invoice_parsings.error_message',
    'invoice_parsings.error_details',
    'notifications.location_id',
    'notifications.user_id',
    'notifications.action_url',
    'notifications.dedup_key',
    'notifications.is_read',
    'notification_reads.deleted_at',
] as const;

const RUNTIME_SCHEMA_STATEMENTS = [
    `CREATE EXTENSION IF NOT EXISTS pgcrypto`,

    `CREATE TABLE IF NOT EXISTS categories (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
    )`,
    `ALTER TABLE categories ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid()`,
    `ALTER TABLE categories ADD COLUMN IF NOT EXISTS name VARCHAR(255)`,
    `ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,

    `CREATE TABLE IF NOT EXISTS laboratories (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
    )`,
    `ALTER TABLE laboratories ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid()`,
    `ALTER TABLE laboratories ADD COLUMN IF NOT EXISTS name VARCHAR(255)`,
    `ALTER TABLE laboratories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,

    `CREATE TABLE IF NOT EXISTS therapeutic_actions (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
    )`,
    `ALTER TABLE therapeutic_actions ADD COLUMN IF NOT EXISTS id UUID DEFAULT gen_random_uuid()`,
    `ALTER TABLE therapeutic_actions ADD COLUMN IF NOT EXISTS name VARCHAR(255)`,
    `ALTER TABLE therapeutic_actions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,

    `CREATE TABLE IF NOT EXISTS suppliers (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        rut VARCHAR(20) UNIQUE,
        business_name VARCHAR(255),
        fantasy_name VARCHAR(255),
        address TEXT,
        city VARCHAR(100),
        region VARCHAR(100),
        commune VARCHAR(100),
        phone_1 VARCHAR(50),
        phone_2 VARCHAR(50),
        contact_email VARCHAR(255),
        email_orders VARCHAR(255),
        email_billing VARCHAR(255),
        website VARCHAR(255),
        sector VARCHAR(100),
        payment_terms VARCHAR(50) DEFAULT 'CONTADO',
        lead_time_days INTEGER DEFAULT 7,
        metadata JSONB DEFAULT '{}'::jsonb,
        is_active BOOLEAN DEFAULT true,
        status VARCHAR(50) DEFAULT 'ACTIVE',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        deactivated_at TIMESTAMP,
        deactivation_reason TEXT
    )`,

    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS fantasy_name VARCHAR(255)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS address TEXT`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS city VARCHAR(100)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS region VARCHAR(100)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS commune VARCHAR(100)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS phone_1 VARCHAR(50)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS phone_2 VARCHAR(50)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS email_orders VARCHAR(255)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS email_billing VARCHAR(255)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS website VARCHAR(255)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS sector VARCHAR(100)`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS payment_terms VARCHAR(50) DEFAULT 'CONTADO'`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS lead_time_days INTEGER DEFAULT 7`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}'::jsonb`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE'`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP`,
    `ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS deactivation_reason TEXT`,
    `UPDATE suppliers SET status = 'ACTIVE' WHERE status IS NULL`,

    `CREATE TABLE IF NOT EXISTS purchase_orders (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        supplier_id UUID,
        target_warehouse_id UUID,
        status VARCHAR(50) DEFAULT 'DRAFT',
        total_amount INTEGER DEFAULT 0,
        delivery_date TIMESTAMP,
        items JSONB DEFAULT '[]'::jsonb,
        notes TEXT,
        created_by TEXT,
        approved_by TEXT,
        received_by TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS supplier_id UUID`,
    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS total_amount INTEGER DEFAULT 0`,
    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS delivery_date TIMESTAMP`,
    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]'::jsonb`,
    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS notes TEXT`,
    `ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()`,

    `CREATE TABLE IF NOT EXISTS purchase_order_items (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        purchase_order_id UUID NOT NULL,
        sku VARCHAR(50) NOT NULL,
        name VARCHAR(150),
        quantity_ordered INTEGER NOT NULL,
        quantity_received INTEGER DEFAULT 0,
        cost_price NUMERIC(10, 2) DEFAULT 0,
        lot_number TEXT,
        expiry_date TIMESTAMPTZ
    )`,

    `ALTER TABLE purchase_order_items ADD COLUMN IF NOT EXISTS quantity_received INTEGER DEFAULT 0`,
    `ALTER TABLE purchase_order_items ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10, 2) DEFAULT 0`,
    `ALTER TABLE purchase_order_items ADD COLUMN IF NOT EXISTS lot_number TEXT`,
    `ALTER TABLE purchase_order_items ADD COLUMN IF NOT EXISTS expiry_date TIMESTAMPTZ`,
    `CREATE INDEX IF NOT EXISTS idx_purchase_order_items_po_sku ON purchase_order_items(purchase_order_id, sku)`,

    `CREATE TABLE IF NOT EXISTS shipments (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        origin_warehouse_id UUID,
        target_warehouse_id UUID,
        origin_location_id UUID,
        destination_location_id UUID,
        status VARCHAR(50) DEFAULT 'PENDING',
        type VARCHAR(50),
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        items JSONB DEFAULT '[]'::jsonb,
        transport_data JSONB DEFAULT '{}'::jsonb,
        documents JSONB DEFAULT '[]'::jsonb,
        valuation NUMERIC DEFAULT 0,
        created_by UUID,
        notes TEXT
    )`,

    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS origin_warehouse_id UUID`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS target_warehouse_id UUID`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS origin_location_id UUID`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS destination_location_id UUID`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]'::jsonb`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS transport_data JSONB DEFAULT '{}'::jsonb`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS documents JSONB DEFAULT '[]'::jsonb`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS valuation NUMERIC DEFAULT 0`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS created_by UUID`,
    `ALTER TABLE shipments ADD COLUMN IF NOT EXISTS notes TEXT`,

    `CREATE TABLE IF NOT EXISTS shipment_items (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        shipment_id UUID,
        product_id UUID,
        sku VARCHAR(50),
        name VARCHAR(255),
        quantity INTEGER NOT NULL,
        batch_id UUID,
        created_at TIMESTAMP DEFAULT NOW(),
        condition VARCHAR(50) DEFAULT 'GOOD',
        notes TEXT
    )`,

    `ALTER TABLE shipment_items ADD COLUMN IF NOT EXISTS product_id UUID`,
    `ALTER TABLE shipment_items ADD COLUMN IF NOT EXISTS batch_id UUID`,
    `ALTER TABLE shipment_items ADD COLUMN IF NOT EXISTS condition VARCHAR(50) DEFAULT 'GOOD'`,
    `ALTER TABLE shipment_items ADD COLUMN IF NOT EXISTS notes TEXT`,
    `CREATE INDEX IF NOT EXISTS idx_shipment_items_shipment_id ON shipment_items(shipment_id)`,
    `CREATE INDEX IF NOT EXISTS idx_shipment_items_batch_id ON shipment_items(batch_id)`,

    `CREATE TABLE IF NOT EXISTS product_suppliers (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        product_id UUID NOT NULL,
        supplier_id UUID NOT NULL,
        supplier_sku VARCHAR(100),
        last_cost NUMERIC(10, 2) DEFAULT 0,
        is_preferred BOOLEAN DEFAULT false,
        delivery_days INTEGER DEFAULT 1,
        created_at TIMESTAMP DEFAULT NOW(),
        last_invoice_date DATE,
        invoice_count INTEGER DEFAULT 0,
        last_invoice_cost NUMERIC(15, 2),
        average_cost NUMERIC(15, 2),
        supplier_product_name TEXT
    )`,

    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS supplier_sku VARCHAR(100)`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS last_cost NUMERIC(10, 2) DEFAULT 0`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS is_preferred BOOLEAN DEFAULT false`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS delivery_days INTEGER DEFAULT 1`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS last_invoice_date DATE`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS invoice_count INTEGER DEFAULT 0`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS last_invoice_cost NUMERIC(15, 2)`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS average_cost NUMERIC(15, 2)`,
    `ALTER TABLE product_suppliers ADD COLUMN IF NOT EXISTS supplier_product_name TEXT`,
    `CREATE UNIQUE INDEX IF NOT EXISTS product_suppliers_product_id_supplier_id_key ON product_suppliers(product_id, supplier_id)`,

    `CREATE TABLE IF NOT EXISTS invoice_parsings (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        supplier_rut VARCHAR(20),
        supplier_name VARCHAR(200),
        supplier_address TEXT,
        supplier_phone TEXT,
        supplier_email TEXT,
        supplier_website TEXT,
        supplier_activity TEXT,
        supplier_fantasy_name TEXT,
        document_type VARCHAR(50) DEFAULT 'FACTURA',
        invoice_number VARCHAR(50),
        issue_date DATE,
        due_date DATE,
        net_amount NUMERIC(15, 2),
        tax_amount NUMERIC(15, 2),
        total_amount NUMERIC(15, 2),
        discount_amount NUMERIC(15, 2) DEFAULT 0,
        parsed_items JSONB DEFAULT '[]'::jsonb,
        document_notes TEXT,
        raw_ai_response JSONB,
        ai_provider VARCHAR(50),
        ai_model VARCHAR(100),
        processing_time_ms INTEGER,
        confidence_score NUMERIC(5, 2),
        validation_warnings JSONB DEFAULT '[]'::jsonb,
        status VARCHAR(50) DEFAULT 'PENDING',
        total_items INTEGER DEFAULT 0,
        mapped_items INTEGER DEFAULT 0,
        unmapped_items INTEGER DEFAULT 0,
        supplier_id UUID,
        supplier_created BOOLEAN DEFAULT false,
        account_payable_id UUID,
        reception_id UUID,
        original_file_type VARCHAR(50),
        original_file_name VARCHAR(255),
        original_file_size INTEGER,
        original_file_hash VARCHAR(64),
        original_file_data TEXT,
        location_id UUID,
        created_by TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        validated_by TEXT,
        validated_at TIMESTAMP,
        processed_by TEXT,
        processed_at TIMESTAMP,
        rejected_by TEXT,
        rejected_at TIMESTAMP,
        rejection_reason TEXT,
        error_message TEXT,
        error_details JSONB
    )`,

    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_rut VARCHAR(20)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_name VARCHAR(200)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_address TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_phone TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_email TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_website TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_activity TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_fantasy_name TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS document_type VARCHAR(50) DEFAULT 'FACTURA'`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS invoice_number VARCHAR(50)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS issue_date DATE`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS due_date DATE`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS net_amount NUMERIC(15, 2)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(15, 2)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS total_amount NUMERIC(15, 2)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(15, 2) DEFAULT 0`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS parsed_items JSONB DEFAULT '[]'::jsonb`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS document_notes TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS raw_ai_response JSONB`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS ai_provider VARCHAR(50)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS ai_model VARCHAR(100)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(5, 2)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS validation_warnings JSONB DEFAULT '[]'::jsonb`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PENDING'`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS total_items INTEGER DEFAULT 0`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS mapped_items INTEGER DEFAULT 0`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS unmapped_items INTEGER DEFAULT 0`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_id UUID`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS supplier_created BOOLEAN DEFAULT false`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS account_payable_id UUID`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS reception_id UUID`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS original_file_type VARCHAR(50)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS original_file_name VARCHAR(255)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS original_file_size INTEGER`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS original_file_hash VARCHAR(64)`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS original_file_data TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS location_id UUID`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS created_by TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS validated_by TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS validated_at TIMESTAMP`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS processed_by TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS rejected_by TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS rejection_reason TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS error_message TEXT`,
    `ALTER TABLE invoice_parsings ADD COLUMN IF NOT EXISTS error_details JSONB`,

    `CREATE TABLE IF NOT EXISTS app_settings (
        key TEXT PRIMARY KEY,
        value TEXT,
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS system_configs (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        config_key TEXT UNIQUE NOT NULL,
        config_value TEXT,
        is_encrypted BOOLEAN NOT NULL DEFAULT false,
        config_type TEXT NOT NULL DEFAULT 'STRING',
        description TEXT,
        category TEXT,
        created_by TEXT,
        updated_by TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS cash_register_sessions (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        terminal_id UUID,
        user_id TEXT,
        status VARCHAR(50) DEFAULT 'OPEN',
        opening_amount NUMERIC(15, 2) DEFAULT 0,
        closing_amount NUMERIC(15, 2) DEFAULT 0,
        opened_at TIMESTAMP DEFAULT NOW(),
        closed_at TIMESTAMP,
        notes TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS financial_accounts (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        location_id UUID,
        name VARCHAR(255),
        type VARCHAR(50),
        balance NUMERIC(15, 2) DEFAULT 0,
        is_active BOOLEAN DEFAULT true,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS monthly_closings (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        month INT NOT NULL,
        year INT NOT NULL,
        real_cash_income NUMERIC(12, 2) DEFAULT 0,
        real_bank_income NUMERIC(12, 2) DEFAULT 0,
        total_sales_income NUMERIC(12, 2) GENERATED ALWAYS AS (real_cash_income + real_bank_income) STORED,
        fixed_expenses NUMERIC(12, 2) DEFAULT 0,
        variable_expenses NUMERIC(12, 2) DEFAULT 0,
        payroll_cost NUMERIC(12, 2) DEFAULT 0,
        social_security_cost NUMERIC(12, 2) DEFAULT 0,
        tax_cost NUMERIC(12, 2) DEFAULT 0,
        net_result NUMERIC(12, 2) GENERATED ALWAYS AS (
            (real_cash_income + real_bank_income) -
            (fixed_expenses + variable_expenses + payroll_cost + social_security_cost + tax_cost)
        ) STORED,
        status TEXT DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'CLOSED')),
        notes TEXT,
        closed_by UUID,
        closed_at TIMESTAMP,
        reopen_reason TEXT,
        reopened_by UUID,
        reopened_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW(),
        UNIQUE(month, year)
    )`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS month INT`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS year INT`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS real_cash_income NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS real_bank_income NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS fixed_expenses NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS variable_expenses NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS payroll_cost NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS social_security_cost NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS tax_cost NUMERIC(12, 2) DEFAULT 0`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'DRAFT'`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS notes TEXT`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS closed_by UUID`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS reopen_reason TEXT`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS reopened_by UUID`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS reopened_at TIMESTAMP`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE monthly_closings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()`,
    `CREATE UNIQUE INDEX IF NOT EXISTS monthly_closings_month_year_key ON monthly_closings(month, year)`,

    `CREATE TABLE IF NOT EXISTS monthly_closing_entries (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        month INT NOT NULL CHECK (month BETWEEN 1 AND 12),
        year INT NOT NULL CHECK (year BETWEEN 2020 AND 2100),
        direction TEXT NOT NULL CHECK (direction IN ('IN', 'OUT')),
        category TEXT NOT NULL CHECK (
            category IN (
                'CASH',
                'TRANSFER_IN',
                'CARD_INSTALLMENT',
                'DAILY_EXPENSE',
                'TRANSFER_OUT',
                'PAYROLL',
                'FIXED_EXPENSE',
                'TAX',
                'OWNER_WITHDRAWAL'
            )
        ),
        description TEXT,
        reference_date DATE NOT NULL,
        amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
        created_by UUID,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
    )`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS month INT`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS year INT`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS direction TEXT`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS category TEXT`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS description TEXT`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS reference_date DATE`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS amount NUMERIC(14, 2)`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS created_by UUID`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()`,
    `ALTER TABLE monthly_closing_entries ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()`,
    `CREATE INDEX IF NOT EXISTS idx_mce_month_year ON monthly_closing_entries (year, month)`,
    `CREATE INDEX IF NOT EXISTS idx_mce_category ON monthly_closing_entries (category)`,

    `CREATE TABLE IF NOT EXISTS treasury_transactions (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        account_id UUID,
        amount NUMERIC(15, 2) DEFAULT 0,
        type VARCHAR(50) DEFAULT 'IN',
        description TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        created_by TEXT
    )`,

    `CREATE TABLE IF NOT EXISTS treasury_remittances (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        location_id UUID,
        terminal_id UUID,
        source_terminal_id UUID,
        cashier_id TEXT,
        received_by TEXT,
        created_by TEXT,
        amount NUMERIC(15, 2) DEFAULT 0,
        cash_count_diff NUMERIC(15, 2) DEFAULT 0,
        status VARCHAR(50) DEFAULT 'PENDING_RECEIPT',
        notes TEXT,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS refunds (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        sale_id UUID,
        terminal_id UUID,
        session_id UUID,
        location_id UUID,
        user_id TEXT,
        ticket_number TEXT,
        total_amount NUMERIC(15, 2) DEFAULT 0,
        refund_method VARCHAR(50) DEFAULT 'CASH',
        status VARCHAR(50) DEFAULT 'COMPLETED',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS notifications (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        type VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
        severity VARCHAR(50) NOT NULL DEFAULT 'INFO',
        title TEXT NOT NULL,
        message TEXT NOT NULL,
        metadata JSONB DEFAULT '{}'::jsonb,
        location_id UUID,
        user_id UUID,
        action_url TEXT,
        dedup_key TEXT UNIQUE,
        is_read BOOLEAN DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS notification_reads (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        notification_id UUID,
        user_id UUID,
        read_at TIMESTAMPTZ,
        deleted_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    )`,

    `CREATE TABLE IF NOT EXISTS attendance_logs (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id UUID,
        location_id UUID,
        type VARCHAR(50),
        timestamp TIMESTAMP DEFAULT NOW(),
        created_at TIMESTAMP DEFAULT NOW()
    )`,

    `ALTER TABLE sales ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'COMPLETED'`,
    `ALTER TABLE sales ADD COLUMN IF NOT EXISTS session_id UUID`,
    `ALTER TABLE locations ADD COLUMN IF NOT EXISTS email VARCHAR(255)`,
    `ALTER TABLE locations ADD COLUMN IF NOT EXISTS manager_id UUID`,
    `ALTER TABLE locations ADD COLUMN IF NOT EXISTS config JSONB DEFAULT '{}'::jsonb`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS category VARCHAR(100)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS dci TEXT`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS units_per_box INTEGER DEFAULT 1`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS price_sell_box NUMERIC(15, 2)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS price_sell_unit NUMERIC(15, 2)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_net NUMERIC(15, 2)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_percent NUMERIC(5, 2) DEFAULT 19`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_minimo_seguridad INTEGER DEFAULT 0`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_total INTEGER DEFAULT 0`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS format VARCHAR(50) DEFAULT 'CAJA'`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS laboratory VARCHAR(100)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS isp_register VARCHAR(50)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS is_bioequivalent BOOLEAN DEFAULT false`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS requires_prescription BOOLEAN DEFAULT false`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS es_frio BOOLEAN DEFAULT false`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS barcode VARCHAR(50)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS location_id UUID`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS comisionable BOOLEAN DEFAULT false`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS registration_source VARCHAR(50)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS is_express_entry BOOLEAN DEFAULT false`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS source_system VARCHAR(50)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS deactivated_by VARCHAR(255)`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS deactivation_reason TEXT`,
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS condicion_venta VARCHAR(10) DEFAULT 'VD'`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS barcode VARCHAR(50)`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS stock_actual INTEGER DEFAULT 0`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS units_per_box INTEGER DEFAULT 1`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS laboratory VARCHAR(100)`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS is_retail_lot BOOLEAN DEFAULT false`,
    `UPDATE products
        SET condicion_venta = CASE UPPER(TRIM(COALESCE(condicion_venta, 'VD')))
            WHEN 'VD' THEN 'VD'
            WHEN 'R' THEN 'R'
            WHEN 'RR' THEN 'RR'
            WHEN 'RCH' THEN 'RCH'
            WHEN 'LIBRE' THEN 'VD'
            WHEN 'VENTA_DIRECTA' THEN 'VD'
            WHEN 'RECETA_SIMPLE' THEN 'R'
            WHEN 'RECETA_RETENIDA' THEN 'RR'
            WHEN 'RECETA_CHEQUE' THEN 'RCH'
            ELSE 'VD'
        END
        WHERE condicion_venta IS DISTINCT FROM CASE UPPER(TRIM(COALESCE(condicion_venta, 'VD')))
            WHEN 'VD' THEN 'VD'
            WHEN 'R' THEN 'R'
            WHEN 'RR' THEN 'RR'
            WHEN 'RCH' THEN 'RCH'
            WHEN 'LIBRE' THEN 'VD'
            WHEN 'VENTA_DIRECTA' THEN 'VD'
            WHEN 'RECETA_SIMPLE' THEN 'R'
            WHEN 'RECETA_RETENIDA' THEN 'RR'
            WHEN 'RECETA_CHEQUE' THEN 'RCH'
            ELSE 'VD'
        END`,
    `ALTER TABLE products ALTER COLUMN condicion_venta SET DEFAULT 'VD'`,
    `DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'products_condicion_venta_canonical'
        ) THEN
            ALTER TABLE products
            ADD CONSTRAINT products_condicion_venta_canonical
            CHECK (condicion_venta IS NULL OR condicion_venta IN ('VD', 'R', 'RR', 'RCH'));
        END IF;
    END $$`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS config JSONB DEFAULT '{}'::jsonb`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS printer_config JSONB DEFAULT '{}'::jsonb`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS module_number VARCHAR(50)`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS current_cashier_id UUID`,
    `ALTER TABLE terminals ADD COLUMN IF NOT EXISTS session_id UUID`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP`,
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45)`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS terminal_id UUID`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS user_id TEXT`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'OPEN'`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS opening_amount NUMERIC(15, 2) DEFAULT 0`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS opened_at TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS closed_at TIMESTAMP`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS notes TEXT`,
    `ALTER TABLE cash_register_sessions ADD COLUMN IF NOT EXISTS closed_by_user_id TEXT`,
    `ALTER TABLE cash_movements ADD COLUMN IF NOT EXISTS session_id UUID`,
    `ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS product_id UUID`,
    `ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS product_name VARCHAR(255)`,
    `ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(15, 2) DEFAULT 0`,
    `ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS timestamp TIMESTAMP DEFAULT NOW()`,
    `ALTER TABLE sale_items ADD COLUMN IF NOT EXISTS refunded_quantity INTEGER DEFAULT 0`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE'`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS loyalty_points INTEGER DEFAULT 0`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'::text[]`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS health_tags TEXT[] DEFAULT '{}'::text[]`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_visit TIMESTAMP`,
    `UPDATE customers SET status = 'ACTIVE' WHERE status IS NULL`,
    `UPDATE customers SET loyalty_points = 0 WHERE loyalty_points IS NULL`,
    `UPDATE customers SET tags = '{}'::text[] WHERE tags IS NULL`,
    `UPDATE customers SET health_tags = '{}'::text[] WHERE health_tags IS NULL`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS method VARCHAR(50) DEFAULT 'PIN'`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS observation TEXT`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS evidence_photo_url TEXT`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS overtime_minutes INTEGER DEFAULT 0`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS overtime_approved BOOLEAN DEFAULT false`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS overtime_approved_by UUID`,
    `ALTER TABLE attendance_logs ADD COLUMN IF NOT EXISTS overtime_approval_notes TEXT`,
    `UPDATE attendance_logs SET method = 'PIN' WHERE method IS NULL`,
    `UPDATE attendance_logs SET overtime_minutes = 0 WHERE overtime_minutes IS NULL`,
    `UPDATE attendance_logs SET overtime_approved = false WHERE overtime_approved IS NULL`,
    `ALTER TABLE notifications ADD COLUMN IF NOT EXISTS location_id UUID`,
    `ALTER TABLE notifications ADD COLUMN IF NOT EXISTS user_id UUID`,
    `ALTER TABLE notifications ADD COLUMN IF NOT EXISTS action_url TEXT`,
    `ALTER TABLE notifications ADD COLUMN IF NOT EXISTS dedup_key TEXT`,
    `ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false`,
    `ALTER TABLE notification_reads ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ`,
] as const;

export async function ensureMinimalRuntimeSchema(client: Queryable) {
    for (const statement of RUNTIME_SCHEMA_STATEMENTS) {
        await client.query(statement);
    }
}
